name: 'Install backend dependencies'
description: 'Set up Python environment and install backend dependencies'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: 'pip'
        cache-dependency-path: backend/dev-dependencies.lock
    - name: Install dependencies
      shell: bash
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        make install/dev